environment:
  AV_PROJECTS: 'c:\projects'
  AV_BF_M2: 'c:\projects\m2'
  AV_BF_SOURCE: 'c:\projects\bioformats'

# Note that only Oracle JDK is provided.
  matrix:
    - java: 1.8
      build: maven
    - java: 1.8
      build: ant
      ant_version: 1.10.1
    - java: 1.7
      build: maven
    - java: 1.7
      build: ant
      ant_version: 1.9.9

cache:
  - '%AV_BF_M2% -> appveyor.yml'

os: 'Visual Studio 2015'
clone_folder: '%AV_BF_SOURCE%'
clone_depth: 5
platform: x64

init:
  - git config --global core.autocrlf input
  - if [%build%] == [ant] appveyor-retry cinst -y ant --version %ant_version%
  - refreshenv
  - 'if [%java%] == [1.7] set "JAVA_HOME=C:\Program Files\Java\jdk1.7.0"'
  - 'if [%java%] == [1.8] set "JAVA_HOME=C:\Program Files\Java\jdk1.8.0"'
  - PATH=%JAVA_HOME%\bin;%PATH%
  - 'if [%build%] == [maven] set "MAVEN_OPTS=-Dmaven.repo.local=%AV_BF_M2%"'
  - 'if [%build%] == [ant] set "ANT_OPTS=-Dmaven.repo.local=%AV_BF_M2%"'

build_script:
  - tools\test-build %build%

#artifacts:
#  - path: 'components\bundles\bioformats_package\target\*.zip'
#  - path: 'components\bundles\bioformats_package\target\*.jar'
#  - path: 'components\bundles\bioformats_package\target\*.tar.*'
#  - path: 'artifacts\bioformats_package.jar'
#  - path: 'artifacts\bftools.zip'
