language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2
  - downloads

addons:
  apt_packages:
    - git

jdk:
  - oraclejdk11
  - oraclejdk8

env:
  - BUILD=maven
  - BUILD=ant

matrix:
  fast_finish: true
  exclude:
  - jdk: oraclejdk11
    env: BUILD=ant

script:
  - ./tools/test-build $BUILD
