language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

addons:
  apt_packages:
    - git
    - cmake
    - build-essential

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

env:
  - BUILD=maven_findbugs
  - BUILD=cppwrap
  - BUILD=sphinx_html
  - BUILD=ant

matrix:
  fast_finish: true
  allow_failures:
    - env: "BUILD=cppwrap"

before_install:
  - if [[ $BUILD == 'sphinx_html' ]]; then pip install --user flake8 Sphinx==1.2.3; fi

install:
  - if [[ $BUILD != 'ant' ]] && [[ $BUILD != 'sphinx_html' ]]; then git fetch --tags; fi
  - if [[ $BUILD == 'maven_findbugs' ]]; then mvn install -DskipTests=true; fi

script:
  - ./tools/test-build $BUILD

matrix:
  exclude:
    - jdk: openjdk6
      env: BUILD=sphinx_html
    - jdk: oraclejdk7
      env: BUILD=sphinx_html
    - jdk: oraclejdk7
      env: BUILD=cppwrap
    - jdk: openjdk6
      env: BUILD=cppwrap
