---
language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2
  - downloads

addons:
  apt:
    packages:
    - git
    - ant

jdk:
  - openjdk11
  - openjdk8

env:
  - BUILD=maven
  - BUILD=ant

matrix:
  fast_finish: true
  exclude:
  - jdk: openjdk11
    env: BUILD=ant
  - jdk: openjdk8
    env: BUILD=maven

script:
  - ./tools/test-build $BUILD

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    jdk: openjdk8
    all_branches: true
    tags: false
