language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2
  - downloads

addons:
  apt_packages:
    - git

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7

env:
  - BUILD=maven
  - BUILD=ant

matrix:
  fast_finish: true
  exclude:
  - jdk: oraclejdk9
    env: BUILD=ant
  - jdk: openjdk7
    env: BUILD=ant

before_install:
  - if [[ $BUILD == 'ant' ]]; then pip install --user flake8 Sphinx; fi

script:
  - ./tools/test-build $BUILD
